### ISSUE TITLE
Recursive classes are not supported

### ISSUE THREAD

**Issue by geomagilles** [avro-kotlin/avro4k#77] opened 2020-11-03 08:31 UTC
For Example:
```
@Serializable
data class User(
    val child: User?
)
```
Can be serialized using Json:
```
val msg = User(User(null))
println(Json.encodeToString(msg)) // {"child":{"child":null}}
```
But failed to be serialized using Avro
```
Avro.default.encodeToByteArray(User.serializer(), msg) 
```
throws a stackoverflow of numerous:
```
	at com.sksamuel.avro4k.schema.ClassSchemaFor.buildField(ClassSchemaFor.kt:70)
	at com.sksamuel.avro4k.schema.ClassSchemaFor.dataClassSchema(ClassSchemaFor.kt:55)
	at com.sksamuel.avro4k.schema.ClassSchemaFor.schema(ClassSchemaFor.kt:43)
	at com.sksamuel.avro4k.schema.NullableSchemaFor.schema(SchemaFor.kt:123)
```

**Comment by thake** [comment] 2020-11-03 09:35
@geomagilles Thanks for reporting the issue. This is actually a duplicate of #37 which was incorrectly closed as "won't fix". Closing this issue as a duplicate.

**Closed by thake** 2020-11-03 09:35 UTC
