### ISSUE TITLE
Performance bottleneck at RecordNaming

### ISSUE THREAD

**Issue by twinprime** [avro-kotlin/avro4k#151] opened 2023-07-25 06:00 UTC
Hi, I am not sure if this is a known problem.

I was doing a simple benchmark of Avro4k and discovered that when Unions are involved, e.g. a sealed interface, a lot of CPU time (like 30% for my case) is spent on `RecordNaming.invoke(String, List<Annotation>, NamingStrategy)`. I used VisualVM to verify.

This is one of the thing that makes Avro4K much slower than jackson-dataformat-avro. Its 2-3x slower for my test case.

**Comment by Chuckame** [comment] 2023-07-25 08:05
Thanks for the benchmark. Can you put at least a screenshot of visualvm of CPU Time tab ? or at most the file ?

We know that there is still reflection that could be replaced, and a lot of re-computation on some cases.

**Comment by twinprime** [comment] 2023-07-25 09:21
No problem, I uploaded the src and a screen shot here

[https://github.com/twinprime/avro-benchmark](https://github.com/twinprime/avro-benchmark)

**Comment by Chuckame** [comment] 2023-07-28 12:52
Thanks. I'll try to fix this

**Comment by Chuckame** [comment] 2023-08-28 22:45
I'm currently working on #148 that should improve the performances, I'll let you informed

**Comment by thake** [comment] 2024-01-21 20:21
A huge performance improvement is planned for version 2. See https://github.com/avro-kotlin/avro4k/issues/160#issuecomment-1711616190

**Comment by Chuckame** [comment] 2024-05-03 22:22
Duplicate of #199

**Closed by Chuckame** 2024-05-03 22:22 UTC
Labels: enhancement

**Comment by Chuckame** [comment] 2024-05-09 13:48
FYI @twinprime I just move your project to avro4k to allow us benchmarking easily for the next releases. See #208
